### PR TITLE
fix: made ECR type checker flexible to accept the server w/o https

### LINKED ISSUE #110: ECR Login fails in Packer 1.8.3
#### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue

Without any changes to the Packer HCL template, Packer builds are now failing with the error:
```
Error fetching ECR credentials: failed to parse the ECR URL: account-id.dkr.ecr.us-east-1.amazonaws.com
==> build.docker.shift: parse "account-id.dkr.ecr.us-east-1.amazonaws.com": invalid URI for request
==> build.docker.shift: it should be either of the form `public.ecr.aws/<registry_alias>/<registry_name>` or `<account number>.dkr.ecr.<region>.amazonaws.com`
Build 'build.docker.shift' errored after 76 milliseconds 463 microseconds: Error fetching ECR credentials: failed to parse the ECR URL: account-id.dkr.ecr.us-east-1.amazonaws.com
parse "account-id.dkr.ecr.us-east-1.amazonaws.com": invalid URI for request
it should be either of the form `public.ecr.aws/<registry_alias>/<registry_name>` or `<account number>.dkr.ecr.<region>.amazonaws.com`
```
(I have substituted the account id number with "account-id" string above)
#### Reproduction Steps

Steps to reproduce this issue

`packer build` with an ECR login.

### Packer version
1.8.3
From `packer version`

### Operating system and Environment details
Ubuntu 22.04, macOS 12.4

### PR DESCRIPTION
**Pull request by devashish-patel**
Resolves #110

### CODE REVIEW

File: post-processor/docker-push/post-processor_test.go [hunk 1]
```diff
@@ -35,27 +35,39 @@ func TestPostProcessor_ImplementsPostProcessor(t *testing.T) {
...
+	if typ != docker.Private {
+		msg := fmt.Sprintf("ECR type should be %v", docker.Private)
+		t.Fatal(msg)
+	}
+
+	// Known Unknown
 	typ, _ = awsConfig.GetEcrType("google.com")
-	if typ != docker.Invalid {
-		msg := fmt.Sprintf("ECR type should be %v", docker.Invalid)
+	if typ != docker.Private {
```
Comment (lbajolet-hashicorp) [inline post-processor/docker-push/post-processor_test.go:66]: I know the current code behaves like this now that we forcefully introduce a schema, and I'd imagine before the current change, if one specified `https://google.com` this would end-up in the `docker.Private` state, so this is probably out-of-scope for this PR, but is there any heuristic we can use to weed out easy invalids like this one?
Naively I'd think something like checking if the host is not the the shape of `\.dkr\.ecr\.[^.]+\.amazonaws\.com` we know it's not a private ECR URL?
Maybe I'm overthinking this, but I'd for sure prefer we reject more explicitely when the URI's not an ECR one, AFAICT there's basically two shapes for those so we can pinpoint them more accurately imho.

**Review by lbajolet-hashicorp — APPROVED** [review]
I just have a comment on the current behaviour for the `GetECRType` with regards to invalid URIs, I feel we can do better, but it's probably outside the scope of this PR.

The code as proposed LGTM!

File: post-processor/docker-push/post-processor_test.go (hunk 1 above)
Comment (devashish-patel) [reply post-processor/docker-push/post-processor_test.go:66]: Actually, before we introduced this code, we did not have any checks. We used to rely upon the AWS SDK. My thought process is to filter out ECR Public/Private URLs if we can otherwise let the AWS SDK handle the error raising as it used to be. And one more thing is that this part of the code is executed only for the AWS, so this is a minor edge case.

Comment (nywilken) [reply post-processor/docker-push/post-processor_test.go:66]: I'm in the same light that we can probably do a bit more than force the HTTPS schema. It looks to me that the check for the protocol is not necessary at all, and that we should support URLs both with and without the schema. Is my observation correct? 

That said, it looks like you are using the GetEcrType to determine if an authorization token should be obtained for the Public ECR repository or for a Private repository. The difference being just the region. Is that correct? 

If so I think we can probably have logic that says if login server host is public.ecr.aws then we should get a PublicAuthorization token, for everything else we should treat as private. That said it is not clear to me if a user can CNAME the public gallery URL to something custom to the user, which in that case could be an issue for the auto detection. If CNAMing is an option should there be a configuration argument `public_ecr_gallery (bool)` that if true would get a Public authorization token? 


Lastly for the docker login command it looks like it does not matter if you pass it a login server with or without a protocol. So this should not be an issue unless I'm mistaken on the supported values.

Comment (nywilken) [reply post-processor/docker-push/post-processor_test.go:66]: > Maybe I'm overthinking this, but I'd for sure prefer we reject more explicitely when the URI's not an ECR one, AFAICT there's basically two shapes for those so we can pinpoint them more accurately imho.

I don't you are over thinking here. Generally speaking we should try to validate for these values when possible. I don't know if it is as simple as checking for AWS owned domain if CNAMing is possible. Which is probably why the original code relied on the API to fail. This is not me saying we shouldn't it is more like we need to do research to make sure it does not run into the same issues as checking for a schema on the URL.

File: builder/docker/ecr_login.go [hunk 2]
```diff
@@ -38,39 +37,30 @@ type AwsAccessConfig struct {
 	// communicate with AWS. Learn how to set
 	// this.
 	Profile string `mapstructure:"aws_profile" required:"false"`
+	// The flag to identify whether to push docker image to Public _or_ Private
+	// ECR. If the user sets this to `true` from the config, we will forcefully
+	// try to push to Public ECR otherwise set this from code based on the
+	// given LoginServer value
+	PublicEcrGallery bool `mapstructure:"public_ecr_gallery" required:"false"`
```
[the remark this answers is not in the document]
Comment (lbajolet-hashicorp) [reply builder/docker/ecr_login.go:44]: OK, now that I looked at the implementation, I think I misunderstood this flag's use. I assumed that we removed all kinds of automatic detection with the introduction of this flag, but this is not the case, this flag bypasses the check.

Maybe we should rename it to `aws_force_use_public_ecr`? That'd make the intent clearer I think.
If we don't go the `force` route, for consistency I'd recommend prefixing the option name with `aws_` still, it'd make it clear this setting is AWS-specific.

File: docs/builders/docker.mdx [hunk 3]
```diff
@@ -601,6 +601,57 @@ post-processors {
...
+    },
+    {
+        "type": "docker-push",
+        "ecr_login": true,
+        "aws_access_key": "YOUR KEY HERE",
+        "aws_secret_key": "YOUR SECRET KEY HERE",
+        "login_server": "https://public.ecr.aws/j9y7g6y8/dev_hc_pkr_dkr_test_1"
+    }
+        ]
+        ]
```
Comment (lbajolet-hashicorp) [inline docs/builders/docker.mdx:630]: The indentation looks off here, is it automatically formatted by the renderer? Otherwise I'd recommend fixing this, it makes it hard to read.

**Review by lbajolet-hashicorp — COMMENTED** [review]
I have a few comments/nits on the code, the logic looks OK to me. I'll approve when they're addressed
